name: CI

on: 
  push:
    tags:
      - v*

jobs:  
  build:    
    runs-on: ubuntu-latest
    container: itkach/alpine-haskell-stack19:8.6.5

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        echo $PWD
        ls -la
        stack --version
        stack config set system-ghc --global true
        stack build --allow-different-user
